databases:
  - name: db
    databaseName: db_x9cj
    user: Deploy-Shift
    region: singapore

services:
  - type: web
    name: Deploy-Shift
    env: ruby
    region: singapore
    plan: free
    buildCommand: "bundle install && yarn install"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

